### ISSUE TITLE
git fastclone 1.2.7 fails on mac: git-fastclone.rb:33:in `parse_update_info'

### ISSUE THREAD

**Issue by michaelkarrer81** [square/git-fastclone#44]
# Steps to reproduce:

1.) Install ```git-fastclone``` on macos
2.) Try git-fastclone with ```git fastclone https://github.com/square/git-fastclone.git```

## Result:
```
Traceback (most recent call last):
        8: from /usr/local/bin/git-fastclone:23:in `<main>'
        7: from /usr/local/bin/git-fastclone:23:in `load'
        6: from /Library/Ruby/Gems/2.6.0/gems/git-fastclone-1.2.7/bin/git-fastclone:22:in `<top (required)>'
        5: from /Library/Ruby/Gems/2.6.0/gems/git-fastclone-1.2.7/lib/git-fastclone.rb:124:in `run'
        4: from /Library/Ruby/Gems/2.6.0/gems/git-fastclone-1.2.7/lib/git-fastclone.rb:207:in `clone'
        3: from /Library/Ruby/Gems/2.6.0/gems/git-fastclone-1.2.7/lib/git-fastclone.rb:228:in `update_submodules'
        2: from /Library/Ruby/Gems/2.6.0/gems/git-fastclone-1.2.7/lib/git-fastclone.rb:228:in `each'
        1: from /Library/Ruby/Gems/2.6.0/gems/git-fastclone-1.2.7/lib/git-fastclone.rb:229:in `block in update_submodules'
/Library/Ruby/Gems/2.6.0/gems/git-fastclone-1.2.7/lib/git-fastclone.rb:33:in `parse_update_info': undefined method `[]' for nil:NilClass (NoMethodError)
```

The line that produces the error:
```[line.strip.match(/'([^']*)'$/)[1], line.strip.match(/\(([^)]*)\)/)[1]]```
in git-fastclone.rb
```
# Contains helper module UrlHelper and execution class GitFastClone::Runner
module GitFastClone
  # Helper methods for fastclone url operations
  module UrlHelper
    def path_from_git_url(url)
      File.basename(url, '.git')
    end
    module_function :path_from_git_url

    def parse_update_info(line)
      [line.strip.match(/'([^']*)'$/)[1], line.strip.match(/\(([^)]*)\)/)[1]]
    end
    module_function :parse_update_info
```

**Comment by justinseanmartin** [comment]
I'm not able to reproduce the issue with various Ruby versions. If you can still reproduce this, which version of git are you running? It shouldn't ever hit this codepath with the repro you supplied, [because there is no `.gitmodules` file at the root of this project's repo](https://github.com/square/git-fastclone/blob/master/lib/git-fastclone.rb#L220). You could add `puts "=== #{line}"` [before the call to `parse_update_info`](https://github.com/square/git-fastclone/blob/master/lib/git-fastclone.rb#L229) to get a better sense of what is happening.

Sorry for not responding sooner. If this is still a problem that you're willing to help investigate please re-open.
